-- BlueTasks Supabase PostgreSQL schema
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  telegram_id text unique not null,
  username text,
  first_name text,
  last_name text,
  balance bigint not null default 0 check (balance >= 0),
  referred_by text,
  referral_count integer not null default 0 check (referral_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id text primary key,
  name text not null,
  description text,
  reward bigint not null check (reward > 0),
  daily_limit integer not null check (daily_limit > 0),
  kind text not null default 'task',
  active boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists public.task_claims (
  id bigint generated by default as identity primary key,
  telegram_id text not null references public.users(telegram_id) on delete cascade,
  task_id text not null references public.tasks(id) on delete restrict,
  reward bigint not null,
  claimed_at timestamptz not null default now()
);

create index if not exists task_claims_user_day_idx
on public.task_claims(telegram_id, task_id, claimed_at);

create table if not exists public.reward_ledger (
  id bigint generated by default as identity primary key,
  telegram_id text not null references public.users(telegram_id) on delete cascade,
  amount bigint not null,
  type text not null,
  reference_id text,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.withdrawals (
  id bigint generated by default as identity primary key,
  telegram_id text not null references public.users(telegram_id) on delete cascade,
  amount bigint not null check (amount >= 1500),
  payout_details text not null,
  status text not null default 'pending' check (status in ('pending','approved','paid','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.increment_referral_count(p_telegram_id text)
returns void language sql security definer set search_path=public as $$
  update users set referral_count=referral_count+1, updated_at=now()
  where telegram_id=p_telegram_id;
$$;

create or replace function public.claim_task(p_telegram_id text, p_task_id text)
returns json language plpgsql security definer set search_path=public as $$
declare
  u users%rowtype;
  t tasks%rowtype;
  used_count integer;
begin
  select * into u from users where telegram_id=p_telegram_id for update;
  if not found then raise exception 'User not found'; end if;

  select * into t from tasks where id=p_task_id and active=true;
  if not found then raise exception 'Task not found'; end if;

  select count(*) into used_count
  from task_claims
  where telegram_id=p_telegram_id and task_id=p_task_id
    and claimed_at >= date_trunc('day', now());

  if used_count >= t.daily_limit then
    raise exception 'Daily limit reached';
  end if;

  insert into task_claims(telegram_id,task_id,reward) values(p_telegram_id,p_task_id,t.reward);
  update users set balance=balance+t.reward, updated_at=now() where telegram_id=p_telegram_id;
  insert into reward_ledger(telegram_id,amount,type,reference_id,note)
  values(p_telegram_id,t.reward,'task',p_task_id,'Task reward');

  return json_build_object('reward',t.reward,'balance',u.balance+t.reward);
end;
$$;

create or replace function public.request_withdrawal(
  p_telegram_id text, p_amount bigint, p_payout_details text
) returns json language plpgsql security definer set search_path=public as $$
declare
  u users%rowtype;
  w withdrawals%rowtype;
begin
  if p_amount < 1500 then raise exception 'Minimum withdrawal is 1500 BLC'; end if;
  select * into u from users where telegram_id=p_telegram_id for update;
  if not found then raise exception 'User not found'; end if;
  if u.balance < p_amount then raise exception 'Insufficient balance'; end if;

  update users set balance=balance-p_amount, updated_at=now() where telegram_id=p_telegram_id;
  insert into withdrawals(telegram_id,amount,payout_details)
  values(p_telegram_id,p_amount,p_payout_details) returning * into w;
  insert into reward_ledger(telegram_id,amount,type,reference_id,note)
  values(p_telegram_id,-p_amount,'withdrawal',w.id::text,'Withdrawal request');

  return json_build_object('withdrawal_id',w.id,'balance',u.balance-p_amount);
end;
$$;

create or replace function public.set_withdrawal_status(
  p_withdrawal_id bigint, p_status text
) returns json language plpgsql security definer set search_path=public as $$
declare
  w withdrawals%rowtype;
begin
  if p_status not in ('approved','paid','rejected') then raise exception 'Invalid status'; end if;
  select * into w from withdrawals where id=p_withdrawal_id for update;
  if not found then raise exception 'Withdrawal not found'; end if;

  if p_status='rejected' and w.status <> 'rejected' then
    update users set balance=balance+w.amount, updated_at=now() where telegram_id=w.telegram_id;
    insert into reward_ledger(telegram_id,amount,type,reference_id,note)
    values(w.telegram_id,w.amount,'withdrawal_refund',w.id::text,'Rejected withdrawal refund');
  end if;

  update withdrawals set status=p_status, updated_at=now() where id=p_withdrawal_id;
  return json_build_object('id',p_withdrawal_id,'status',p_status);
end;
$$;

-- Seed tasks
insert into public.tasks(id,name,description,reward,daily_limit,kind,sort_order)
values
('premium3','Premium 3-Minute Ad','Complete a premium 3-minute task.',30,3,'premium',1),
('ad5','Quick Task 5','Complete the task and earn 5 BLC.',5,20,'ad',2),
('ad6','Quick Task 6','Complete the task and earn 6 BLC.',6,20,'ad',3),
('ad7','Quick Task 7','Complete the task and earn 7 BLC.',7,20,'ad',4),
('ad10','Quick Task 10','Complete the task and earn 10 BLC.',10,20,'ad',5)
on conflict(id) do update set
name=excluded.name, description=excluded.description, reward=excluded.reward,
daily_limit=excluded.daily_limit, kind=excluded.kind, sort_order=excluded.sort_order;

-- RLS is intentionally not relied on here because the server uses the Supabase service-role key.
-- NEVER expose SUPABASE_SERVICE_ROLE_KEY in frontend code.
